ALTER TABLE categorias 
ADD COLUMN IF NOT EXISTS estado BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

ALTER TABLE productos ADD COLUMN descripcion TEXT;
ALTER TABLE productos ADD COLUMN imagen VARCHAR(255);